name: Update Wiki

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: CuBoulder/ghaction-wiki-publish@main
        if: ${{ github.event.pull_request.merged }}
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

