name: Update Wiki

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: CuBoulder/ghaction-wiki-publish@main
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
